development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: redis://redistogo:3cb969dd13a12c7d3410ecfce7b54dbf@tarpon.redistogo.com:9635/
  channel_prefix: bitter-api_production
